# Generated by Django 4.1.7 on 2023-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_username_alter_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='username',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
